const propsToRestoreMapList = [
  {
    obj: window,
    propsList: [
      'addEventListener',
      'alert',
      'atob',
      'blur',
      'btoa',
      'clearInterval',
      'clearTimeout',
      'close',
      'confirm',
      'focus',
      'getComputedStyle',
      'getSelection',
      'matchMedia',
      'moveBy',
      'moveTo',
      'open',
      'print',
      'prompt',
      'removeEventListener',
      'resizeBy',
      'resizeTo',
      'scrollBy',
      'scrollTo',
      'setInterval',
      'setTimeout',
      'stop',
    ],
  },
  {
    obj: document,
    propsList: [
      'addEventListener',
      'adoptNode',
      'close',
      'createAttribute',
      'createComment',
      'createDocumentFragment',
      'createElement',
      'createEvent',
      'createTextNode',
      'execCommand',
      'getElementById',
      'getElementsByClassName',
      'getElementsByName',
      'getElementsByTagName',
      'hasFocus',
      'importNode',
      'normalize',
      'normalizeDocument',
      'open',
      'querySelector',
      'querySelectorAll',
      'removeEventListener',
      'renameNode',
      'write',
      'writeln',
    ],
  },
];

export default propsToRestoreMapList;
